[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700

[supervisord]
nodaemon=true

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[program:auth-server]
command=java -Djava.net.preferIPv4Stack=true -Dconf.path=/opt/jftse/auth-server/target/dist -jar /opt/jftse/auth-server/target/auth-server.jar
autostart=true
autorestart=true
directory=/opt/jftse/auth-server/target
redirect_stderr=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0

[program:game-server]
command=java -Djava.net.preferIPv4Stack=true -Dconf.path=/opt/jftse/game-server/target/dist -jar /opt/jftse/game-server/target/game-server.jar
autostart=true
autorestart=true
directory=/opt/jftse/game-server/target
redirect_stderr=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0

[program:chat-server]
command=java -Djava.net.preferIPv4Stack=true -Dconf.path=/opt/jftse/chat-server/target/dist -jar /opt/jftse/chat-server/target/chat-server.jar
autostart=true
autorestart=true
directory=/opt/jftse/chat-server/target
redirect_stderr=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0

[program:relay-server]
command=java -Djava.net.preferIPv4Stack=true -Dconf.path=/opt/jftse/relay-server/target/dist -jar /opt/jftse/relay-server/target/relay-server.jar
autostart=true
autorestart=true
directory=/opt/jftse/relay-server/target
redirect_stderr=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
