[supervisord]
nodaemon=true
user=root

[program:auth-server]
command=/opt/java/jdk-21/bin/java -Xms32m -Xmx384m -Djava.net.preferIPv4Stack=true -jar ../auth-server.jar
autostart=true
autorestart=true
startsecs=10
directory=/opt/jftse/auth-server/target/dist
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:game-server]
command=/opt/java/jdk-21/bin/java -Xms32m -Xmx384m -Djava.net.preferIPv4Stack=true -jar ../game-server.jar
autostart=true
autorestart=true
startsecs=10
directory=/opt/jftse/game-server/target/dist
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:chat-server]
command=/opt/java/jdk-21/bin/java -Xms32m -Xmx384m -Djava.net.preferIPv4Stack=true -jar ../chat-server.jar
autostart=true
autorestart=true
startsecs=10
directory=/opt/jftse/chat-server/target/dist
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:relay-server]
command=/opt/java/jdk-21/bin/java -Xms32m -Xmx384m -Djava.net.preferIPv4Stack=true -jar ../relay-server.jar
autostart=true
autorestart=true
startsecs=10
directory=/opt/jftse/relay-server/target/dist
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:ac-server]
command=/opt/java/jdk-21/bin/java -Xms32m -Xmx256m -Djava.net.preferIPv4Stack=true -jar ../ac-server.jar
autostart=true
autorestart=true
startsecs=10
directory=/opt/jftse/ac-server/target/dist
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
